# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # Specify the version you desire her
      - image: circleci/php:7.4-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: vagrant
          TEST_DATABASE_URL: http://127.0.0.1:8000
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: vagrant
          POSTGRES_DB: circleci-tests
          POSTGRES_PASSWORD: vagrant
    steps:
      - add_ssh_keys:
          fingerprints:
            "a5:3d:c0:4b:4e:2f:bd:e4:9f:9c:86:a1:8e:2b:2a:e7"
      - checkout
      - run:
          name: "Prepare Environment"
          command: |
            sudo -E apt-get update && sudo -E apt-get install libpq-dev
            sudo -E docker-php-ext-install pdo_pgsql && sudo -E docker-php-ext-enable pdo_pgsql

      - run:
          name: "Create Environment file"
          command: |
            cp .env.testing .env
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install  --ignore-platform-reqs --no-interaction --prefer-dist --optimize-autoloader --no-dev
      - run: ./vendor/bin/phpunit

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      - run:
          name: "Create database and run migration"
          command: |
            php artisan migrate --env=testing
      #      - run:
      #          name: "Run Http Tests"
      #          command: ./vendor/bin/phpunit tests/Feature

      - run:
          name: "Install Dusk and Chrome Drivers"
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
            composer require --dev laravel/dusk
            php artisan dusk:chrome-driver
      - run:
          name: Start Chrome Driver
          command: |
            ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve --no-reload
          background: true

      - run:
          name: Run Browser Tests Tests
          command: php artisan dusk
