version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: vagrant
          TEST_DATABASE_URL: http://127.0.0.1:8000
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: vagrant
          POSTGRES_DB: circleci-tests
          POSTGRES_PASSWORD: vagrant
    steps:
      - add_ssh_keys:
          fingerprints:
            "a5:3d:c0:4b:4e:2f:bd:e4:9f:9c:86:a1:8e:2b:2a:e7"
      - checkout
      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update && sudo docker-php-ext-install zip
            sudo apt-get update && sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql && sudo docker-php-ext-enable pdo_pgsql
            sudo docker-php-ext-install pcntl
            sudo apt-get update

      - run:
          name: "Create Environment file"
          command: |
            cp .env.testing .env
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install
      - run: composer require --dev laravel/dusk

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Generate App key"
          command: php artisan key:generate

      - run:
          name: "Create database and run migration"
          command: |
            php artisan migrate

      - run:
          name: "Install Dusk and Chrome Drivers"
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
            composer require --dev laravel/dusk
            php artisan dusk:chrome-driver

      - run:
          name: Start Chrome Driver
          command: |
            ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve --no-reload
          background: true

      - run:
          name: Run Browser Tests Tests
          command: php artisan dusk
